### ISSUE TITLE
Support the masquerade option for the 99_simp firewalld zone

### ISSUE THREAD

**Issue by number41** [simp/pupmod-simp-simp_firewalld#42]
I need to enable masquerading in the 99_simp zone to support some applications.

**Comment by michael-riddle** [comment]
We will look into adding this feature in the near future. Thank you for your ticket!

**Comment by michael-riddle** [comment]
Closing, the following PR took care of this: https://github.com/simp/pupmod-simp-simp_firewalld/pull/43
